In [8]:
import cv2
import numpy as np
import matplotlib.pylab as plt

# Image Location.
image_path1 = '..\images\greenBernie.jpg'
image_path2 = '..\images\space.jpg'

img1 = cv2.imread(image_path1)
img2 = cv2.imread(image_path2)

# Extract width and height from image
height1, width1 = img1.shape[:2]
height2, width2 = img2.shape[:2]

x = (width2 - width1)//2
y = height2 - height1
w = x + width1
h = y + height1

print(x)
print(y)
print(w)
print(h)

0
0
640
480


In [9]:
chromakey = img1[:10, :10, :]
print(chromakey)
offset = 10

hsv_chroma = cv2.cvtColor(chromakey, cv2.COLOR_BGR2HSV)
hsv_img = cv2.cvtColor(img1, cv2.COLOR_BGR2HSV)

cv2.imshow("hsv_chroma",hsv_chroma)
cv2.imshow("hsv_img", hsv_img)
cv2.waitKey()
cv2.destroyAllWindows()

[[[ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]]

 [[ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]]

 [[ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]]

 [[ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]]

 [[ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]]

 [[ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]
  [ 31 254  54]]

 [[ 31 254  54]
  [ 31 254  

In [3]:
print(hsv_chroma.shape)

(10, 10, 3)


In [10]:
chroma_h = hsv_chroma[:,:,0]
print(chroma_h)
print(chroma_h.shape)
print(chroma_h.min())
lower = np.array([chroma_h.min()-offset, 100, 100])
print(lower)
upper = np.array([chroma_h.max()+offset, 255, 255])
print(upper)

[[57 57 57 57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57 57 57 57]]
(10, 10)
57
[ 47 100 100]
[ 67 255 255]


In [11]:
mask = cv2.inRange(hsv_img, lower, upper)
mask_inv = cv2.bitwise_not(mask)

In [12]:
cv2.imshow("Mask", mask)
cv2.waitKey()
cv2.destroyAllWindows()

In [13]:
roi = img2[y:h, x:w]
fg = cv2.bitwise_and(img1, img1, mask=mask_inv)
bg = cv2.bitwise_and(roi, roi, mask=mask)
img2[y:h, x:w] = fg + bg

cv2.imshow('chromakey', img1)
cv2.imshow('added', img2)
cv2.waitKey()
cv2.destroyAllWindows()