In [3]:
!pip install torch

Defaulting to user installation because normal site-packages is not writeable
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
   ---------------------------------------- 0.0/110.9 MB ? eta -:--:--
   - -------------------------------------- 3.9/110.9 MB 21.3 MB/s eta 0:00:06
   -- ------------------------------------- 7.3/110.9 MB 18.9 MB/s eta 0:00:06
   ---- ----------------------------------- 11.8/110.9 MB 19.1 MB/s eta 0:00:06
   ------ --------------------------------- 19.1/110.9 MB 23.2 MB/s eta 0:00:04
   ---------- ----------------------------- 28.6/110.9 MB 27.5 MB/s eta 0:00:03
   ------------ --------------------------- 35.4/110.9 MB 28.5 MB/s eta 0:00:03
   --------------- ------------------------ 44.0/110.9 MB 30.1 MB/s eta 0:00:03
   ------------------- -------------------- 53.7/110.9 MB 32.1 MB/s eta 0:00:02
   ---------------------- ----------------- 61.3/110.9 MB 32.4 MB/s et


[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import torch

In [3]:
# Random image tensor with 3 channels, height 5, width 5
img_t = torch.rand(3,5,5) 
weights = torch.tensor([0.2126, 0.7152, 0.0722])
batch_t = torch.randn(2, 3, 5, 5)

print(img_t)
print("--------------------------------")
print(batch_t)

tensor([[[0.5319, 0.5006, 0.3556, 0.3863, 0.8209],
         [0.2590, 0.7460, 0.1874, 0.5610, 0.7330],
         [0.4976, 0.9875, 0.9688, 0.6510, 0.9701],
         [0.2368, 0.4512, 0.4888, 0.9477, 0.0541],
         [0.5660, 0.6323, 0.8660, 0.4769, 0.5341]],

        [[0.1735, 0.0474, 0.7923, 0.3261, 0.7731],
         [0.6279, 0.6652, 0.6067, 0.0098, 0.0713],
         [0.9614, 0.7342, 0.2000, 0.5910, 0.8751],
         [0.5055, 0.6062, 0.5582, 0.7793, 0.0398],
         [0.4933, 0.9915, 0.3872, 0.6540, 0.2046]],

        [[0.7748, 0.5323, 0.7391, 0.0763, 0.0437],
         [0.8867, 0.0799, 0.3903, 0.5471, 0.2375],
         [0.3369, 0.2019, 0.8132, 0.7882, 0.6175],
         [0.4201, 0.9440, 0.5220, 0.8163, 0.6338],
         [0.1359, 0.9670, 0.0710, 0.9991, 0.8094]]])
--------------------------------
tensor([[[[-0.9356,  0.7068, -0.5996, -0.7676, -0.3769],
          [-0.4170, -1.6965, -0.4167,  1.1121, -0.0882],
          [-0.2006, -0.7972,  0.9840, -0.1002, -0.7572],
          [ 0.7594, -1.38

In [4]:
img_gray_naive = img_t.mean(-3)
print(img_gray_naive)
# -3 refers to the channel dimension in a 3D tensor (C, H, W)
batch_gray_naive = batch_t.mean(-3)
print(batch_gray_naive.shape)

tensor([[0.4934, 0.3601, 0.6290, 0.2629, 0.5459],
        [0.5912, 0.4970, 0.3948, 0.3726, 0.3473],
        [0.5986, 0.6412, 0.6607, 0.6767, 0.8209],
        [0.3875, 0.6672, 0.5230, 0.8478, 0.2426],
        [0.3984, 0.8636, 0.4414, 0.7100, 0.5160]])
torch.Size([2, 5, 5])


### Tensor Storage

A Pytorch is basically just a wrapper or view around the actual memory/data, and because indexing or transforming a tensor usually does not create new copies that data but instead shares the same underlying Stoarage. This makes tensor to be efficient

In [7]:
points = torch.tensor([[4.0, 1.0], [2.0, 2.0], [0.0, 3.0]])
point_storage = points.storage()

print(point_storage)
print("Index at 0 in point_storage: ", point_storage[0])
print("Index at 1 in point_stoarge: ", points.storage()[1])
print("Set point Stoarage at 0")

point_storage[0] = 2.0
print(points)

 4.0
 1.0
 2.0
 2.0
 0.0
 3.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
Index at 0 in point_storage:  4.0
Index at 1 in point_stoarge:  1.0
Set point Stoarage at 0
tensor([[2., 1.],
        [2., 2.],
        [0., 3.]])


### Tensor Metadata
* size, offset, and stride

In [10]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
print(second_point)

print(second_point.storage_offset())

# Set value within tensor
second_point[0] = 10
print(points)

tensor([5., 3.])
2
tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])


In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)

points_t = points.t()
print(points_t)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
tensor([[4., 5., 2.],
        [1., 3., 1.]])


In [14]:
print(id(points.storage()) == id(points_t.storage()))
print(points.stride())
print(points_t.stride())

True
(2, 1)
(1, 2)


In [15]:
some_t = torch.ones(3, 4, 5)
print(some_t)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
