In [1]:
import torch

def collocation_points(*args):
    grids = torch.meshgrid(*args, indexing='ij')
    coord = torch.stack(grids, dim=len(args)).reshape(-1, len(args))
    return coord

In [2]:
nt = 3
nx = 3
t = torch.linspace(0, 1, nt)
x = torch.linspace(-1, 1, nx)
cdata = collocation_points(t, x)

print(f'{cdata.shape}\n{cdata}')

torch.Size([9, 2])
tensor([[ 0.0000, -1.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  1.0000],
        [ 0.5000, -1.0000],
        [ 0.5000,  0.0000],
        [ 0.5000,  1.0000],
        [ 1.0000, -1.0000],
        [ 1.0000,  0.0000],
        [ 1.0000,  1.0000]])


In [3]:
ny = 3
y = torch.linspace(-1, 1, ny)
cdata = collocation_points(t, y, x)
print(f'{cdata.shape}\n{cdata}')

torch.Size([27, 3])
tensor([[ 0.0000, -1.0000, -1.0000],
        [ 0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000,  1.0000],
        [ 0.0000,  0.0000, -1.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  1.0000],
        [ 0.0000,  1.0000, -1.0000],
        [ 0.0000,  1.0000,  0.0000],
        [ 0.0000,  1.0000,  1.0000],
        [ 0.5000, -1.0000, -1.0000],
        [ 0.5000, -1.0000,  0.0000],
        [ 0.5000, -1.0000,  1.0000],
        [ 0.5000,  0.0000, -1.0000],
        [ 0.5000,  0.0000,  0.0000],
        [ 0.5000,  0.0000,  1.0000],
        [ 0.5000,  1.0000, -1.0000],
        [ 0.5000,  1.0000,  0.0000],
        [ 0.5000,  1.0000,  1.0000],
        [ 1.0000, -1.0000, -1.0000],
        [ 1.0000, -1.0000,  0.0000],
        [ 1.0000, -1.0000,  1.0000],
        [ 1.0000,  0.0000, -1.0000],
        [ 1.0000,  0.0000,  0.0000],
        [ 1.0000,  0.0000,  1.0000],
        [ 1.0000,  1.0000, -1.0000],
        [ 1.0000,  1.0000,  0.0000],
        [ 1.0000, 

### Initial Condition

In [4]:
u0 = torch.sin(x)
inidata = collocation_points(t[0], x)
print(f'{inidata.shape}\n{inidata}')

torch.Size([3, 2])
tensor([[ 0., -1.],
        [ 0.,  0.],
        [ 0.,  1.]])


In [5]:
u0

tensor([-0.8415,  0.0000,  0.8415])

### Boundary Condition

In [6]:
xbg = torch.FloatTensor([x[0], x[-1]])
bgdata = collocation_points(t, xbg)
print(f'{bgdata.shape}\n{bgdata}')

torch.Size([6, 2])
tensor([[ 0.0000, -1.0000],
        [ 0.0000,  1.0000],
        [ 0.5000, -1.0000],
        [ 0.5000,  1.0000],
        [ 1.0000, -1.0000],
        [ 1.0000,  1.0000]])


In [7]:
class TensorData(torch.utils.data.Dataset):
    def __init__(self, cdata):
        self.cdata = cdata
        self.len = len(cdata)

    def __getitem__(self, index):
        return self.cdata[index]

    def __len__(self):
        return self.len

batch_size = 8
train_loader = torch.utils.data.DataLoader(TensorData(cdata), batch_size=batch_size, shuffle=True)

In [8]:
dataiter = iter(train_loader)
batch_cdata = next(dataiter)
print(batch_cdata)

tensor([[ 1.0000, -1.0000,  1.0000],
        [ 1.0000,  1.0000, -1.0000],
        [ 0.0000, -1.0000,  1.0000],
        [ 0.0000,  1.0000, -1.0000],
        [ 0.0000,  0.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000],
        [ 0.5000,  1.0000,  0.0000],
        [ 1.0000,  0.0000,  1.0000]])


In [ ]:
~~~~